export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_SECTIONS_REQUEST = "GET_SECTIONS_REQUEST";
export const GET_SECTIONS_SUCCESS = "GET_SECTIONS_SUCCESS";
export const GET_SECTIONS_FAILURE = "GET_SECTIONS_FAILURE";

export const GET_SECTIONS_CATEGORIES_REQUEST =
  "GET_SECTIONS_CATEGORIES_REQUEST";
export const GET_SECTIONS_CATEGORIES_SUCCESS =
  "GET_SECTIONS_CATEGORIES_SUCCESS";
export const GET_SECTIONS_CATEGORIES_FAILURE =
  "GET_SECTIONS_CATEGORIES_FAILURE";
